language: python
python:
  - "2.7.13"

install:
  - pip install -r requirements.txt

script:
  - pytest tests/test_views.py
  - pytest tests/test_auth.py
  - nose2 --with-coverage

after_success:
  - coveralls